import { 
  Task, 
  ScheduleEvent, 
  Habit, 
  WorkoutLog, 
  MealPlanItem, 
  BillItem, 
  NoteItem, 
  GoalItem, 
  UserOrbitProfile 
} from "../types";

const getTodayIso = (): string => {
  const d = new Date();
  return d.toISOString().split("T")[0];
};

export const INITIAL_PROFILE: UserOrbitProfile = {
  name: "Alex Vance",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  dailyCalorieTarget: 2200,
  proteinTargetGrams: 160,
  carbsTargetGrams: 220,
  fatTargetGrams: 70,
  waterIntakeOz: 64,
  waterTargetOz: 100,
  sleepHours: 7.5,
  sleepTargetHours: 8.0,
  monthlyBudget: 225000,
};

const today = getTodayIso();

export const INITIAL_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Finalize Project Presentation and Task Outline",
    priority: "P1",
    category: "Work",
    estimatedMinutes: 60,
    completed: false,
    dueDate: today,
    scheduledTime: "09:00",
    tags: ["project", "high-impact"],
    subtasks: [
      { id: "sub-1", title: "Review outline & task list", completed: true, estimatedMinutes: 20 },
      { id: "sub-2", title: "Draft main points and summary", completed: false, estimatedMinutes: 25 },
      { id: "sub-3", title: "Export document", completed: false, estimatedMinutes: 15 },
    ],
    notes: "Ensure all key points are clear for the team meeting.",
    createdAt: today,
  },
  {
    id: "task-2",
    title: "Quarterly Financial Audit & Recurring Subscription Review",
    priority: "P1",
    category: "Finance",
    estimatedMinutes: 45,
    completed: true,
    dueDate: today,
    scheduledTime: "11:30",
    tags: ["budget", "bills"],
    subtasks: [
      { id: "sub-4", title: "Cancel unused cloud storage tier", completed: true, estimatedMinutes: 15 },
      { id: "sub-5", title: "Consolidate gym & streaming receipts", completed: true, estimatedMinutes: 30 },
    ],
    createdAt: today,
  },
  {
    id: "task-3",
    title: "Prepare High-Protein Meal Prep for Mid-Week Focus",
    priority: "P2",
    category: "Nutrition",
    estimatedMinutes: 40,
    completed: false,
    dueDate: today,
    scheduledTime: "18:30",
    tags: ["health", "meal-prep"],
    subtasks: [
      { id: "sub-6", title: "Grill chicken breast & steam broccolini", completed: false, estimatedMinutes: 25 },
      { id: "sub-7", title: "Portion quinoa into glass containers", completed: false, estimatedMinutes: 15 },
    ],
    createdAt: today,
  },
  {
    id: "task-4",
    title: "30-Minute Upper Body Hypertrophy Workout",
    priority: "P2",
    category: "Fitness",
    estimatedMinutes: 35,
    completed: false,
    dueDate: today,
    scheduledTime: "17:00",
    tags: ["workout", "strength"],
    subtasks: [],
    createdAt: today,
  },
  {
    id: "task-5",
    title: "Read Chapter 4 of 'Deep Work' by Cal Newport",
    priority: "P3",
    category: "Learning",
    estimatedMinutes: 30,
    completed: false,
    dueDate: today,
    scheduledTime: "21:00",
    tags: ["reading", "mindset"],
    subtasks: [],
    createdAt: today,
  },
];

export const INITIAL_SCHEDULE: ScheduleEvent[] = [
  {
    id: "evt-1",
    title: "🌅 Orbit Morning Ritual & Hydration",
    startTime: "07:30",
    endTime: "08:15",
    category: "Health",
    isFocusBlock: false,
    completed: true,
    date: today,
  },
  {
    id: "evt-2",
    title: "🧠 Deep Focus Block: Orbit System Spec",
    startTime: "09:00",
    endTime: "10:30",
    category: "Work",
    taskId: "task-1",
    isFocusBlock: true,
    completed: false,
    date: today,
  },
  {
    id: "evt-3",
    title: "☕ Active Recovery Walk & Coffee",
    startTime: "10:30",
    endTime: "11:00",
    category: "Personal",
    isFocusBlock: false,
    completed: true,
    date: today,
  },
  {
    id: "evt-4",
    title: "💰 Financial Audit & Bills Review",
    startTime: "11:30",
    endTime: "12:15",
    category: "Finance",
    taskId: "task-2",
    isFocusBlock: false,
    completed: true,
    date: today,
  },
  {
    id: "evt-5",
    title: "🥗 High-Protein Quinoa & Salmon Bowl",
    startTime: "12:30",
    endTime: "13:15",
    category: "Nutrition",
    isFocusBlock: false,
    completed: false,
    date: today,
  },
  {
    id: "evt-6",
    title: "🏋️ Strength & Conditioning Session",
    startTime: "17:00",
    endTime: "17:45",
    category: "Fitness",
    taskId: "task-4",
    isFocusBlock: true,
    completed: false,
    date: today,
  },
  {
    id: "evt-7",
    title: "🌙 Evening Reflection & Digital Sunset",
    startTime: "21:30",
    endTime: "22:00",
    category: "Personal",
    isFocusBlock: false,
    completed: false,
    date: today,
  },
];

export const INITIAL_HABITS: Habit[] = [
  {
    id: "habit-1",
    title: "16oz Morning Hydration + Electrolytes",
    frequency: "daily",
    category: "Health",
    streakCount: 14,
    completedToday: true,
    historyMap: { [today]: true },
    iconName: "Droplets",
    timeOfDay: "Morning",
    targetCountPerWeek: 7,
  },
  {
    id: "habit-2",
    title: "10-Min Mindfulness / Diaphragmatic Breathing",
    frequency: "daily",
    category: "Health",
    streakCount: 9,
    completedToday: true,
    historyMap: { [today]: true },
    iconName: "BrainCircuit",
    timeOfDay: "Morning",
    targetCountPerWeek: 7,
  },
  {
    id: "habit-3",
    title: "Hit 150g+ Protein Goal",
    frequency: "daily",
    category: "Nutrition",
    streakCount: 6,
    completedToday: false,
    historyMap: {},
    iconName: "Apple",
    timeOfDay: "Anytime",
    targetCountPerWeek: 7,
  },
  {
    id: "habit-4",
    title: "No Screen Time 45 mins Before Bed",
    frequency: "daily",
    category: "Personal",
    streakCount: 4,
    completedToday: false,
    historyMap: {},
    iconName: "Moon",
    timeOfDay: "Evening",
    targetCountPerWeek: 6,
  },
  {
    id: "habit-5",
    title: "Weekly Review & Budget Audit",
    frequency: "weekly",
    category: "Finance",
    streakCount: 3,
    completedToday: true,
    historyMap: { [today]: true },
    iconName: "Wallet",
    timeOfDay: "Afternoon",
    targetCountPerWeek: 1,
  },
];

export const INITIAL_WORKOUTS: WorkoutLog[] = [
  {
    id: "wo-1",
    title: "Upper Body Hypertrophy & Core",
    type: "Strength",
    durationMinutes: 45,
    caloriesBurned: 340,
    intensity: "High",
    date: today,
    exercises: [
      { id: "ex-1", exerciseName: "Dumbbell Incline Bench Press", sets: 4, reps: 10, weightLbs: 65 },
      { id: "ex-2", exerciseName: "Lat Pulldown / Pullups", sets: 4, reps: 10, weightLbs: 140 },
      { id: "ex-3", exerciseName: "Lateral Deltoid Raises", sets: 3, reps: 15, weightLbs: 22.5 },
      { id: "ex-4", exerciseName: "Hanging Leg Raises", sets: 3, reps: 12 },
    ],
    notes: "Great energy on incline press today. Incremental overload target hit.",
  },
];

export const INITIAL_MEALS: MealPlanItem[] = [
  {
    id: "meal-1",
    name: "Avocado & Poached Egg Sourdough Toast",
    mealType: "Breakfast",
    calories: 420,
    proteinGrams: 24,
    carbsGrams: 42,
    fatGrams: 16,
    ingredients: ["2 Eggs", "Sourdough Bread", "1/2 Avocado", "Microgreens", "Chili Flakes"],
    consumed: true,
    date: today,
  },
  {
    id: "meal-2",
    name: "Wild Salmon Quinoa & Roasted Sweet Potato Bowl",
    mealType: "Lunch",
    calories: 580,
    proteinGrams: 45,
    carbsGrams: 52,
    fatGrams: 18,
    ingredients: ["6oz Wild Salmon", "Quinoa", "Roasted Sweet Potato", "Tahini Dressing", "Steamed Broccoli"],
    consumed: true,
    date: today,
  },
  {
    id: "meal-3",
    name: "Grass-Fed Beef or Tofu Stir-Fry with Jasmines Rice",
    mealType: "Dinner",
    calories: 640,
    proteinGrams: 50,
    carbsGrams: 65,
    fatGrams: 20,
    ingredients: ["Lean Beef / Tofu", "Jasmine Rice", "Bell Peppers", "Snap Peas", "Tamari Sauce"],
    consumed: false,
    date: today,
  },
  {
    id: "meal-4",
    name: "Triple Berry Protein Smoothie",
    mealType: "Snack",
    calories: 280,
    proteinGrams: 30,
    carbsGrams: 28,
    fatGrams: 5,
    ingredients: ["Whey / Plant Protein", "Frozen Blueberries", "Almond Milk", "Chia Seeds"],
    consumed: false,
    date: today,
  },
];

export const INITIAL_BILLS: BillItem[] = [
  {
    id: "bill-1",
    name: "Cloud Studio & Infrastructure Hosting",
    amount: 2800.00,
    dueDate: `${today.substring(0, 7)}-28`,
    category: "Utilities",
    recurringFrequency: "Monthly",
    status: "upcoming",
    autoPay: true,
    isRecurring: true,
  },
  {
    id: "bill-2",
    name: "Gym & Wellness Club Membership",
    amount: 6500.00,
    dueDate: `${today.substring(0, 7)}-01`,
    category: "Subscription",
    recurringFrequency: "Monthly",
    status: "paid",
    autoPay: true,
    isRecurring: true,
  },
  {
    id: "bill-3",
    name: "High-Speed Fiber Internet",
    amount: 4200.00,
    dueDate: `${today.substring(0, 7)}-15`,
    category: "Utilities",
    recurringFrequency: "Monthly",
    status: "paid",
    autoPay: false,
    isRecurring: true,
  },
  {
    id: "bill-4",
    name: "Health & Life Insurance Premium",
    amount: 12000.00,
    dueDate: `${today.substring(0, 7)}-25`,
    category: "Insurance",
    recurringFrequency: "Monthly",
    status: "upcoming",
    autoPay: true,
    isRecurring: true,
  },
];

export const INITIAL_NOTES: NoteItem[] = [
  {
    id: "note-1",
    title: "Orbit Design Philosophy & Core Principles",
    content: `# Orbit Operating System Architecture
- **Principle 1: Easy Quick Capture** — Every task, event, or note should be capturable in a few seconds.
- **Principle 2: Smart Daily Planning** — Combine concrete calendar blocks with flexible schedule time gaps.
- **Principle 3: Life Balance Dashboard** — Track the 5 core areas: Focus/Work, Health/Fitness, Nutrition, Wealth/Finance, Mindset.`,
    category: "Work",
    tags: ["manifesto", "design"],
    updatedAt: today,
    isPinned: true,
  },
  {
    id: "note-2",
    title: "Weekly Grocery & Meal Prep Shopping List",
    content: `- 2 lbs Wild Salmon Filets
- 3 Bunches Organic Spinach
- 2 Bags Quinoa
- 1 Dozen Eggs
- Greek Yogurt
- Frozen Mixed Berries`,
    category: "Nutrition",
    tags: ["grocery", "shopping"],
    updatedAt: today,
    isPinned: false,
  },
];

export const INITIAL_GOALS: GoalItem[] = [
  {
    id: "goal-1",
    title: "Achieve Peak Physical Fitness & Energy",
    description: "Build functional strength, hit weekly workout targets, and maintain a healthy nutrition routine.",
    timeframe: "Q3 2026",
    category: "Fitness",
    targetValue: 100,
    currentValue: 72,
    unit: "%",
    color: "emerald",
    linkedTaskIds: ["task-3", "task-4"],
    milestones: [
      { id: "m-1", title: "Consistently log 4 workouts/week for 30 consecutive days", completed: true },
      { id: "m-2", title: "Hit healthy daily protein average", completed: true },
      { id: "m-3", title: "Complete 10,000 steps daily average", completed: false },
    ],
  },
  {
    id: "goal-2",
    title: "Build & Launch Orbit App to 1,000 Active Users",
    description: "Create an intuitive, easy-to-use life planner with smart assistant features.",
    timeframe: "Q4 2026",
    category: "Work",
    targetValue: 1000,
    currentValue: 420,
    unit: "users",
    color: "indigo",
    linkedTaskIds: ["task-1"],
    milestones: [
      { id: "m-4", title: "Finalize Phase 1 design & layout", completed: true },
      { id: "m-5", title: "Integrate Smart Assistant helper", completed: true },
      { id: "m-6", title: "Launch Public Beta & collect user feedback", completed: false },
    ],
  },
  {
    id: "goal-3",
    title: "Emergency Fund & Investment Portfolio Growth",
    description: "Optimize monthly fixed expenses and allocate recurring automated investments into index funds.",
    timeframe: "Year 2026",
    category: "Finance",
    targetValue: 2500000,
    currentValue: 1925000,
    unit: "PHP",
    color: "amber",
    linkedTaskIds: ["task-2"],
    milestones: [
      { id: "m-7", title: "Audit monthly recurring subscriptions", completed: true },
      { id: "m-8", title: "Automate monthly transfer of ₱75,000 into portfolio", completed: true },
      { id: "m-9", title: "Reach ₱2,500,000 liquid capital threshold", completed: false },
    ],
  },
];
